import json
import os

new_phrases = [
  {
    "id": "add001",
    "text": "เป็นอะไรหรือเปล่า",
    "phonetic": "pen a-rai reu-plaao",
    "translation": "妳怎麼了？",
    "audioUrl": "/audio/th/add001.mp3",
    "translationAudioUrl": "/audio/th/add001_tw.mp3",
    "hasAudio": False,
    "order": 101,
    "tags": ["emotion", "thai"],
    "note": "關心對方狀況",
    "ttsText": "เป็นอะไรหรือเปล่า",
    "status": "published",
    "category": "new_phrases",
    "level": "beginner",
    "hashtags": ["#thai", "#emotion"]
  },
  {
    "id": "add002",
    "text": "ไม่โอเคเลย",
    "phonetic": "mai o-kay loei",
    "translation": "完全不OK",
    "audioUrl": "/audio/th/add002.mp3",
    "translationAudioUrl": "/audio/th/add002_tw.mp3",
    "hasAudio": False,
    "order": 102,
    "tags": ["emotion", "thai"],
    "note": "強烈否定情緒",
    "ttsText": "ไม่โอเคเลย",
    "status": "published",
    "category": "new_phrases",
    "level": "beginner",
    "hashtags": ["#thai", "#emotion"]
  },
  {
    "id": "add003",
    "text": "ใจหายเลย",
    "phonetic": "jai haai loei",
    "translation": "心都涼了 / 嚇了一跳",
    "audioUrl": "/audio/th/add003.mp3",
    "translationAudioUrl": "/audio/th/add003_tw.mp3",
    "hasAudio": False,
    "order": 103,
    "tags": ["emotion", "thai"],
    "note": "常用於感到可惜或被嚇到",
    "ttsText": "ใจหายเลย",
    "status": "published",
    "category": "new_phrases",
    "level": "intermediate",
    "hashtags": ["#thai", "#emotion"]
  },
  {
    "id": "add004",
    "text": "น่าจะใช่นะ",
    "phonetic": "naa ja chai na",
    "translation": "應該是吧",
    "audioUrl": "/audio/th/add004.mp3",
    "translationAudioUrl": "/audio/th/add004_tw.mp3",
    "hasAudio": False,
    "order": 104,
    "tags": ["guess", "thai"],
    "note": "不確定語氣",
    "ttsText": "น่าจะใช่นะ",
    "status": "published",
    "category": "new_phrases",
    "level": "beginner",
    "hashtags": ["#thai", "#guess"]
  },
  {
    "id": "add005",
    "text": "ไม่น่าจะใช่",
    "phonetic": "mai naa ja chai",
    "translation": "應該不是",
    "audioUrl": "/audio/th/add005.mp3",
    "translationAudioUrl": "/audio/th/add005_tw.mp3",
    "hasAudio": False,
    "order": 105,
    "tags": ["guess", "thai"],
    "note": "否定推測",
    "ttsText": "ไม่น่าจะใช่",
    "status": "published",
    "category": "new_phrases",
    "level": "beginner",
    "hashtags": ["#thai", "#guess"]
  },
  {
    "id": "add006",
    "text": "แล้วไงต่อ",
    "phonetic": "laeo ngai tor",
    "translation": "然後呢？",
    "audioUrl": "/audio/th/add006.mp3",
    "translationAudioUrl": "/audio/th/add006_tw.mp3",
    "hasAudio": False,
    "order": 106,
    "tags": ["conversation", "thai"],
    "note": "接話用",
    "ttsText": "แล้วไงต่อ",
    "status": "published",
    "category": "new_phrases",
    "level": "beginner",
    "hashtags": ["#thai", "#conversation"]
  },
  {
    "id": "add007",
    "text": "สรุปคือ",
    "phonetic": "sa-rup keu",
    "translation": "總之就是",
    "audioUrl": "/audio/th/add007.mp3",
    "translationAudioUrl": "/audio/th/add007_tw.mp3",
    "hasAudio": False,
    "order": 107,
    "tags": ["conversation", "thai"],
    "note": "整理結論",
    "ttsText": "สรุปคือ",
    "status": "published",
    "category": "new_phrases",
    "level": "intermediate",
    "hashtags": ["#thai", "#conversation"]
  },
  {
    "id": "add008",
    "text": "พอได้แล้ว",
    "phonetic": "por dai laeo",
    "translation": "夠了",
    "audioUrl": "/audio/th/add008.mp3",
    "translationAudioUrl": "/audio/th/add008_tw.mp3",
    "hasAudio": False,
    "order": 108,
    "tags": ["emotion", "thai"],
    "note": "情緒爆發",
    "ttsText": "พอได้แล้ว",
    "status": "published",
    "category": "new_phrases",
    "level": "intermediate",
    "hashtags": ["#thai", "#emotion"]
  },
  {
    "id": "add009",
    "text": "หยุดนะ",
    "phonetic": "yut na",
    "translation": "停下來",
    "audioUrl": "/audio/th/add009.mp3",
    "translationAudioUrl": "/audio/th/add009_tw.mp3",
    "hasAudio": False,
    "order": 109,
    "tags": ["emotion", "thai"],
    "note": "制止他人",
    "ttsText": "หยุดนะ",
    "status": "published",
    "category": "new_phrases",
    "level": "beginner",
    "hashtags": ["#thai", "#emotion"]
  },
  {
    "id": "add010",
    "text": "อย่ามายุ่ง",
    "phonetic": "yaa maa yung",
    "translation": "不要管我",
    "audioUrl": "/audio/th/add010.mp3",
    "translationAudioUrl": "/audio/th/add010_tw.mp3",
    "hasAudio": False,
    "order": 110,
    "tags": ["emotion", "thai"],
    "note": "生氣用語",
    "ttsText": "อย่ามายุ่ง",
    "status": "published",
    "category": "new_phrases",
    "level": "intermediate",
    "hashtags": ["#thai", "#emotion"]
  },
  {
    "id": "add011",
    "text": "หึงเหรอ",
    "phonetic": "heung ror",
    "translation": "吃醋喔？",
    "audioUrl": "/audio/th/add011.mp3",
    "translationAudioUrl": "/audio/th/add011_tw.mp3",
    "hasAudio": False,
    "order": 111,
    "tags": ["love", "thai"],
    "note": "撩人或開玩笑常用",
    "ttsText": "หึงเหรอ",
    "status": "published",
    "category": "new_phrases",
    "level": "beginner",
    "hashtags": ["#thai", "#love"]
  },
  {
    "id": "add012",
    "text": "อย่าคิดไปเอง",
    "phonetic": "yaa kit pai eng",
    "translation": "不要自己亂想",
    "audioUrl": "/audio/th/add012.mp3",
    "translationAudioUrl": "/audio/th/add012_tw.mp3",
    "hasAudio": False,
    "order": 112,
    "tags": ["love", "thai"],
    "note": "感情對話",
    "ttsText": "อย่าคิดไปเอง",
    "status": "published",
    "category": "new_phrases",
    "level": "intermediate",
    "hashtags": ["#thai", "#love"]
  },
  {
    "id": "add013",
    "text": "เออใช่",
    "phonetic": "er chai",
    "translation": "對啊",
    "audioUrl": "/audio/th/add013.mp3",
    "translationAudioUrl": "/audio/th/add013_tw.mp3",
    "hasAudio": False,
    "order": 113,
    "tags": ["daily", "thai"],
    "note": "超口語",
    "ttsText": "เออใช่",
    "status": "published",
    "category": "new_phrases",
    "level": "beginner",
    "hashtags": ["#thai", "#daily"]
  },
  {
    "id": "add014",
    "text": "ไม่รู้สิ",
    "phonetic": "mai roo si",
    "translation": "不知道欸",
    "audioUrl": "/audio/th/add014.mp3",
    "translationAudioUrl": "/audio/th/add014_tw.mp3",
    "hasAudio": False,
    "order": 114,
    "tags": ["daily", "thai"],
    "note": "隨意回答",
    "ttsText": "ไม่รู้สิ",
    "status": "published",
    "category": "new_phrases",
    "level": "beginner",
    "hashtags": ["#thai", "#daily"]
  },
  {
    "id": "add015",
    "text": "แล้วแต่เลย",
    "phonetic": "laeo tae loei",
    "translation": "隨便你",
    "audioUrl": "/audio/th/add015.mp3",
    "translationAudioUrl": "/audio/th/add015_tw.mp3",
    "hasAudio": False,
    "order": 115,
    "tags": ["daily", "thai"],
    "note": "放棄選擇",
    "ttsText": "แล้วแต่เลย",
    "status": "published",
    "category": "new_phrases",
    "level": "beginner",
    "hashtags": ["#thai", "#daily"]
  },
  {
    "id": "add016",
    "text": "อีกแป๊บนึง",
    "phonetic": "eek paep neung",
    "translation": "再一下",
    "audioUrl": "/audio/th/add016.mp3",
    "translationAudioUrl": "/audio/th/add016_tw.mp3",
    "hasAudio": False,
    "order": 116,
    "tags": ["time", "thai"],
    "note": "時間短暫",
    "ttsText": "อีกแป๊บนึง",
    "status": "published",
    "category": "new_phrases",
    "level": "beginner",
    "hashtags": ["#thai", "#time"]
  },
  {
    "id": "add017",
    "text": "ยังไม่ถึง",
    "phonetic": "yang mai teung",
    "translation": "還沒到",
    "audioUrl": "/audio/th/add017.mp3",
    "translationAudioUrl": "/audio/th/add017_tw.mp3",
    "hasAudio": False,
    "order": 117,
    "tags": ["time", "thai"],
    "note": "狀態描述",
    "ttsText": "ยังไม่ถึง",
    "status": "published",
    "category": "new_phrases",
    "level": "beginner",
    "hashtags": ["#thai", "#time"]
  },
  {
    "id": "add018",
    "text": "เสร็จหรือยัง",
    "phonetic": "set reu yang",
    "translation": "好了沒？",
    "audioUrl": "/audio/th/add018.mp3",
    "translationAudioUrl": "/audio/th/add018_tw.mp3",
    "hasAudio": False,
    "order": 118,
    "tags": ["time", "thai"],
    "note": "詢問進度",
    "ttsText": "เสร็จหรือยัง",
    "status": "published",
    "category": "new_phrases",
    "level": "beginner",
    "hashtags": ["#thai", "#time"]
  },
  {
    "id": "add019",
    "text": "ไม่เป็นไรหรอก",
    "phonetic": "mai pen rai rok",
    "translation": "真的沒關係啦",
    "audioUrl": "/audio/th/add019.mp3",
    "translationAudioUrl": "/audio/th/add019_tw.mp3",
    "hasAudio": False,
    "order": 119,
    "tags": ["daily", "thai"],
    "note": "語氣較柔和的安慰",
    "ttsText": "ไม่เป็นไรหรอก",
    "status": "published",
    "category": "new_phrases",
    "level": "beginner",
    "hashtags": ["#thai", "#daily"]
  },
  {
    "id": "add020",
    "text": "แน่ใจนะ",
    "phonetic": "nae jai na",
    "translation": "確定喔？",
    "audioUrl": "/audio/th/add020.mp3",
    "translationAudioUrl": "/audio/th/add020_tw.mp3",
    "hasAudio": False,
    "order": 120,
    "tags": ["conversation", "thai"],
    "note": "再三確認時使用",
    "ttsText": "แน่ใจนะ",
    "status": "published",
    "category": "new_phrases",
    "level": "beginner",
    "hashtags": ["#thai", "#conversation"]
  },
  {
    "id": "add021",
    "text": "ทำไมล่ะ",
    "phonetic": "tam-mai la",
    "translation": "為什麼啦？",
    "audioUrl": "/audio/th/add021.mp3",
    "translationAudioUrl": "/audio/th/add021_tw.mp3",
    "hasAudio": False,
    "order": 121,
    "tags": ["conversation", "thai"],
    "note": "帶有好奇或輕微抱怨的語氣",
    "ttsText": "ทำไมล่ะ",
    "status": "published",
    "category": "new_phrases",
    "level": "beginner",
    "hashtags": ["#thai", "#conversation"]
  },
  {
    "id": "add022",
    "text": "ว่าไงนะ",
    "phonetic": "waa ngai na",
    "translation": "妳說什麼？",
    "audioUrl": "/audio/th/add022.mp3",
    "translationAudioUrl": "/audio/th/add022_tw.mp3",
    "hasAudio": False,
    "order": 122,
    "tags": ["conversation", "thai"],
    "note": "沒聽清楚或感到驚訝時用",
    "ttsText": "ว่าไงนะ",
    "status": "published",
    "category": "new_phrases",
    "level": "beginner",
    "hashtags": ["#thai", "#conversation"]
  },
  {
    "id": "add023",
    "text": "สัญญาเลย",
    "phonetic": "san-yaa loei",
    "translation": "我保證 / 我發誓",
    "audioUrl": "/audio/th/add023.mp3",
    "translationAudioUrl": "/audio/th/add023_tw.mp3",
    "hasAudio": False,
    "order": 123,
    "tags": ["love", "thai"],
    "note": "給予承諾",
    "ttsText": "สัญญาเลย",
    "status": "published",
    "category": "new_phrases",
    "level": "intermediate",
    "hashtags": ["#thai", "#love"]
  },
  {
    "id": "add024",
    "text": "รอตั้งนาน",
    "phonetic": "ror tang naan",
    "translation": "等了好久耶",
    "audioUrl": "/audio/th/add024.mp3",
    "translationAudioUrl": "/audio/th/add024_tw.mp3",
    "hasAudio": False,
    "order": 124,
    "tags": ["time", "thai"],
    "note": "帶點撒嬌或小抱怨的語氣",
    "ttsText": "รอตั้งนาน",
    "status": "published",
    "category": "new_phrases",
    "level": "beginner",
    "hashtags": ["#thai", "#time"]
  },
  {
    "id": "add025",
    "text": "ช่างมันเถอะ",
    "phonetic": "chaang man tur",
    "translation": "算了吧 / 隨他去吧",
    "audioUrl": "/audio/th/add025.mp3",
    "translationAudioUrl": "/audio/th/add025_tw.mp3",
    "hasAudio": False,
    "order": 125,
    "tags": ["emotion", "thai"],
    "note": "表達放棄糾結、看開",
    "ttsText": "ช่างมันเถอะ",
    "status": "published",
    "category": "new_phrases",
    "level": "intermediate",
    "hashtags": ["#thai", "#emotion"]
  }
]

def append_to_file(filepath):
    if not os.path.exists(filepath):
        print(f"File not found: {filepath}")
        return
        
    with open(filepath, 'r', encoding='utf-8') as f:
        data = json.load(f)
        
    # check if they already exist
    existing_ids = set(item.get("id") for item in data)
    
    added_count = 0
    for p in new_phrases:
        if p["id"] not in existing_ids:
            data.append(p)
            added_count += 1
            
    if added_count > 0:
        with open(filepath, 'w', encoding='utf-8') as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
        print(f"Added {added_count} items to {filepath}")
    else:
        print(f"No items added to {filepath} (they might already exist)")

append_to_file('/Users/olga/Desktop/LoopLang/data/th.json')
append_to_file('/Users/olga/Desktop/LoopLang/data/th_all.json')
